### ISSUE TITLE
Gebruik 1 H1 en een paragraph voor de rest!

### ISSUE THREAD

**Issue by Tolga1999** [Prz6/your-tribe-profile-card#4]
https://github.com/Prz6/your-tribe-profile-card/blob/22213c89c677769e25c692d8da203e600f403f40/index.html#L23-L26

ik zou alleen meerdere headings gebruiken als je de containers echt wilt scheiden van elkaar, in dit geval lijkt het dat je 1 component hebt met een H1 (naam) en tekst daaronder (paragraph)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Comment by Prz6** [comment]
Heb het aangepast en de headings verandert naar paragraphs.
